<?xml version="1.0"?>
<package format="3">
  <name>ur10e_robotiq_moveit_config</name>
  <version>0.0.0</version>
  <description>MoveIt configuration for the combined UR10e, Robotiq FT300, and Robotiq 2F-85 robot.</description>
  <maintainer email="maintainer@example.com">Maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_kinematics</exec_depend>
  <exec_depend>moveit_planners</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <exec_depend>moveit_simple_controller_manager</exec_depend>
  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>ur10e_robotiq_description</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>warehouse_ros_sqlite</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
