controller_manager:
  ros__parameters:
    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController

cartesian_impedance_controller:
  ros__parameters:
    base_frame: base_link
    tip_frame: gripper_tcp
    target_topic: ~/target_pose
    use_external_ft: false
    use_coriolis: false
    integral_gain: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    stiffness: [60.0, 60.0, 60.0, 6.0, 6.0, 6.0]
    damping: [15.0, 15.0, 15.0, 1.5, 1.5, 1.5]
    linear_reference_speed: 0.05
    angular_reference_speed: 0.2
    command_timeout: 0.5
